enterprise:
  enabled: true
gateway:
  replicas: 0
proxy:
  enabled: true
  resources:
    requests:
      memory: 10Mi
      cpu: 100m
  ingress:
    enabled: true
  autoscaling:
    enabled: true
  route:
    enabled: true
